- name: Ensure remote media dir exists
  file:
    path: "{{remote_media_dir}}"
    state: directory
    owner: "{{ansible_ssh_user}}"
  sudo: yes

- name: Ensure /usr/local/bin dir exists
  file:
    path: /usr/local/bin
    state: directory
  sudo: yes

- name: Copy evercam_media run init script
  sudo: yes
  template:
    src: run_evercam_media.sh.j2
    dest: /usr/local/bin/run_evercam_media.sh
    owner: root
    group: root
    mode: 0755

- name: Copy evercam_media stop script
  sudo: yes
  template:
    src: stop_evercam_media.sh.j2
    dest: /usr/local/bin/stop_evercam_media.sh
    owner: root
    group: root
    mode: 0755

- name: Copy evercam_media service
  sudo: yes
  template:
    src: evercam_media.service.j2
    dest: /lib/systemd/system/evercam_media.service
    owner: root
    group: root
    mode: 0755

- name: Install the evercam_media init script
  sudo: yes
  template:
    src: evercam_media.conf.j2
    dest: /etc/init/evercam_media.conf
    owner: root
    group: root
    mode: 0755
