- name: Check if Elixir release directory exists
  stat: path={{remote_media_dir}}
  register: release_exists

- include: cleanup.yml

- include: bootstrap.yml

- name: Restart evercam-media
  command: "{{remote_media_dir}}/bin/evercam_media restart"
  when: release_exists.stat.exists == True

- name: Check if evercam-media is running
  command: "{{remote_media_dir}}/bin/evercam_media ping"
  register: ping
  failed_when: "'pong' not in ping.stdout"
  changed_when: "ping.stdout != 'pong'"
