- include: setup.yml
  tags: configure

- include: deploy.yml
  tags: deploy

- name: Stop evercam-media
  shell: stop evercam_media
  sudo: yes
  failed_when: False
  tags: deploy

- name: Start evercam-media
  shell: start evercam_media
  sudo: yes
  failed_when: False
  tags: deploy
