- hosts: "{{target}}"
  user: "{{ansible_ssh_user}}"
  vars_files:
    - vars.yml
    - ../../private_vars_media.yml
  vars:
    - production: True
    - user_name: "{{ansible_ssh_user}}"
  roles:
    - { role: deps, tags: configure }
    - { role: ANXS.postgresql, tags: configure, sudo: yes }
    - { role: monitoring, tags: configure }
    - { role: ffmpeg, tags: configure }
    - { role: nginx, tags: configure }
    - { role: media, tags: deploy,evercam-media }