- name: Add FFMPEG repository
  apt_repository: repo='ppa:mc3man/trusty-media' state=present

- name: Update apt cache
  action: apt update_cache=yes

- name: Install dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - ffmpeg