- name: Install SeaweedFS
  command: "bash -lc 'go get github.com/chrislusf/seaweedfs/weed'"
  tags: configure

- name: Add SeaweedFS volume service
  template:
    src: seaweedfs-volume.conf.j2
    dest: /etc/init/seaweedfs.conf
  tags: deploy,volume

- name: Start SeaweedFS volume service
  command: sudo restart seaweedfs
  tags: deploy,volume

- name: Add seaweedfs master service
  template:
    src: seaweedfs-master.conf.j2
    dest: /etc/init/seaweedfs.conf
  tags: deploy,master

- name: Start SeaweedFS master service
  command: sudo restart seaweedfs
  tags: deploy,master
