- hostname: name=media.evercam.io
  sudo: yes

- name: Ensure /usr/local/bin dir exists
  file: path=/usr/local/bin state=directory
  sudo: yes

- name: Update apt cache
  action: apt update_cache=yes
  sudo: yes

- name: Make sure the required packages are installed
  sudo: yes
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - git
    - iotop
    - htop
    - python-pip
    - libjpeg-dev
    - unattended-upgrades

- name: Check if Goon is present
  stat: path=/usr/local/bin/goon
  register: goon_present

- name: Download Goon
  get_url:
    url: https://github.com/alco/goon/releases/download/v1.1.1/goon_linux_amd64.tar.gz
    dest: /tmp/goon_linux_amd64.tar.gz
  when: goon_present.stat.exists == False

- name: Unpack Goon
  command: tar -xvzf /tmp/goon_linux_amd64.tar.gz
  args:
    chdir: /tmp
    creates: /tmp/goon
  when: goon_present.stat.exists == False

- name: Add Goon to PATH
  sudo: yes
  command: mv /tmp/goon /usr/local/bin
  args:
    creates: /usr/local/bin/goon
    removes: /tmp/goon
  when: goon_present.stat.exists == False

- name: Install Heroku Toolbelt
  shell: wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh

- name: Set fs.file-max
  sysctl: name=fs.file-max value=12000500 state=present
  sudo: yes

- name: Set fs.nr_open
  sysctl: name=fs.nr_open value=20000500 state=present
  sudo: yes

- name: Set net.ipv4.tcp_mem
  sysctl: name=net.ipv4.tcp_mem value='10000000 10000000 10000000' state=present
  sudo: yes

- name: Set net.ipv4.tcp_rmem
  sysctl: name=net.ipv4.tcp_rmem value='8388608 8388608 8388608' state=present
  sudo: yes

- name: Set net.ipv4.tcp_wmem
  sysctl: name=net.ipv4.tcp_wmem value='4096 65536 8388608' state=present
  sudo: yes

- name: Set net.core.rmem_max
  sysctl: name=net.core.rmem_max value=8388608 state=present
  sudo: yes

- name: Set net.core.wmem_max
  sysctl: name=net.core.wmem_max value=8388608 state=present
  sudo: yes
