- name: Source asdf in bashrc
  lineinfile:
    line: "source /home/{{user_name}}/.asdf/asdf.sh"
    dest: "/home/{{user_name}}/.bash_profile"
    create: yes
    owner: "{{user_name}}"
  sudo_user: "{{ user_name }} -i"

- name: Add asdf plugins for Ruby
  command: "bash -lc 'asdf plugin-add ruby https://github.com/HashNuke/asdf-ruby.git'"
  failed_when: false
  sudo_user: "{{ user_name }} -i"

- name: Install Ruby using asdf
  command: "bash -lc 'asdf install ruby 2.3.1'"
  sudo_user: "{{ user_name }} -i"

- name: Set Ruby version using asdf
  command: "bash -lc 'asdf global ruby 2.3.1'"
  sudo_user: "{{ user_name }} -i"

- name: Install Bundler
  command: "bash -lc 'gem install bundler'"
  sudo_user: "{{ user_name }} -i"
