- name: Ensure RVM path exists
  file:
    path='{{ rvm1_install_path }}'
    state=directory
    recurse=yes
    owner='{{ rvm1_user }}'
    group='{{ rvm1_group }}'

- name: Install gems for the API
  sudo_user: "{{ user_name }} -i"
  shell: bundle install --local
  args:
    chdir: "{{evercam_api_dir}}"

- name: Clone production database
  sudo_user: "{{ user_name }} -i"
  shell: ./scripts/create
  args:
    chdir: "{{evercam_api_dir}}"

- name: Run database migrations
  sudo_user: "{{ user_name }} -i"
  shell: NO_FAKE_S3=true bundle exec rake db:migrate
  args:
    chdir: "{{evercam_api_dir}}"

- name: Install gems for the Dashboard
  sudo_user: "{{ user_name }} -i"
  shell: bundle install --local
  args:
    chdir: "{{evercam_dash_dir}}"

- name: Install hex packages for Media
  sudo_user: "{{ user_name }} -i"
  shell: mix deps.get
  args:
    chdir: "{{evercam_media_dir}}"
