- name: Install gems for the Dashboard
  sudo_user: "{{ user_name }} -i"
  shell: bundle install --local
  args:
    chdir: "{{evercam_dash_dir}}"

- name: Install hex packages for Media
  sudo_user: "{{ user_name }} -i"
  shell: mix deps.get
  args:
    chdir: "{{evercam_media_dir}}"
