- name: Update Nginx configuration
  template: src=nginx.conf
            dest=/usr/local/nginx/conf/nginx.conf

- name: Check Nginx configuration
  shell: /usr/local/nginx/sbin/nginx -t
  notify:
    - reload nginx
