- name: Add FFMPEG repository
  apt_repository:
    repo: 'ppa:jonathonf/ffmpeg-3'
    state: present
  failed_when: false

- name: Update apt cache
  apt:
    update_cache: yes
  failed_when: false
  sudo: yes

- name: Install dependencies
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - ffmpeg
