- name: Download Erlang Solutions repository
  get_url:
    url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /tmp/erlang-solutions_1.0_all.deb

- name: Add Erlang Solutions repository
  sudo: yes
  command: dpkg -i erlang-solutions_1.0_all.deb
  args:
    chdir: /tmp

- name: Update apt cache
  sudo: yes
  action: apt update_cache=yes
  failed_when: false

- name: Install dependencies
  sudo: yes
  action: apt pkg={{item}} state=latest
  with_items:
    - elixir
    - esl-erlang

- name: Install hex
  shell: mix local.hex --force
  sudo_user: "{{ user_name }} -i"
  sudo: yes

- name: Install rebar
  shell: mix local.rebar --force
  sudo_user: "{{ user_name }} -i"
  sudo: yes
