- hosts: all
  user: vagrant
  sudo: yes
  vars_files:
    - vars.yml
    - ../elixir_setup/vars.yml
    - ../../private_vars_devops.yml
  vars:
    - production: False
    - user_name: vagrant
  roles:
    - deps
    - { role: "../elixir_setup/ffmpeg"}
    - { role: "../elixir_setup/nginx"}
    - { role: elixir, erlang_version: 18.1, elixir_version: v1.0.5 }
    - nodesource.node
    - rvm_io.rvm1-ruby
    - ANXS.postgresql
    - DavidWittman.redis
    - geerlingguy.memcached
    - evercam
