- name: Register New Relic repository.
  get_url: url=http://download.newrelic.com/debian/newrelic.list
           dest=/etc/apt/sources.list.d/newrelic.list
  sudo: yes

- name: Download New Relic repo key.
  apt_key: url=http://download.newrelic.com/548C16BF.gpg
  sudo: yes

- name: Install New Relic.
  apt: pkg=newrelic-sysmond update_cache=yes
  sudo: yes

- name: Configure New Relic with license key.
  shell: "nrsysmond-config --set license_key={{new_relic_key}}"
  sudo: yes

- name: Start New Relic.
  service: name=newrelic-sysmond state=started
  sudo: yes

- name: Install the restart_evercam script
  sudo: yes
  template:
    src: restart_evercam.conf.j2
    dest: /etc/init/restart_evercam.conf
    owner: root
    group: root
    mode: 0755

- name: Start restart_evercam script
  shell: sudo start restart_evercam
  failed_when: false

- name: Ensure that .aws directory exists
  sudo: yes
  file:
    path: /root/.aws
    state: directory
    mode: 0600

- name: Create aws credentials file
  sudo: yes
  template:
    src: aws_credentials.j2
    dest: /root/.aws/credentials
    mode: 0600

- name: Download AWS Log installer
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py

- name: Configure AWS Logs
  template:
    src: awslogs.conf.j2
    dest: /tmp/awslogs.conf

- name: Install AWS Logs deamon
  sudo: yes
  command: /usr/bin/python /tmp/awslogs-agent-setup.py -n -r eu-west-1 -c /tmp/awslogs.conf