- name: Install monit
  apt: name=monit
  sudo: yes

- name: Configure monit
  template:
    src: monitrc.j2
    dest: "/etc/monit/monitrc"
    mode: 0600
  sudo: yes

- name: Upload evercam-media alert script
  template:
    src: evercam_media_alert.j2
    dest: "/usr/local/bin/evercam_media_alert"
    mode: 0755
  sudo: yes

- name: Reload monit
  service: name=monit state=reloaded
  sudo: yes
